### ISSUE TITLE
Release 4.4 M1 (2021.0.0) [DATASOLR-613]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-solr#727]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATASOLR-613](https://jira.spring.io/browse/DATASOLR-613?redirect=false)** and commented

---
No further details from [DATASOLR-613](https://jira.spring.io/browse/DATASOLR-613?redirect=false)

**Comment by kdebski85** [comment]
DATASOLR-606 says that there will be no Spring Data Solr for 4.4.
Could you please confirm that Spring Data Solr is going to be discontinued?
Should we use SolrJ instead?

**Comment by christophstrobl** [comment]
@kdebski85 sorry for the confusion - this seems to be a glitch in the release automation. This project will only see patch updates for already released versions, till it's finally moved to the [attic](https://github.com/spring-attic).
Going forward, feel free to foster a fork of the project or consider using SolrJ directly.
